# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    identifier: "87899141"
    url: /
    weight: 10
  - name: Papers
    identifier: faf688e0
    url: /#papers
    weight: 20
  - name: Projects
    identifier: b2205457
    url: projects/
    weight: 30
  - name: Experience
    identifier: 9f49adac
    url: experience/
    weight: 40
  - name: Courses
    identifier: a277f655
    url: courses/
    weight: 50
