hugoblox:
  schema: "2.0"
  identity:
    name: Barra Roantree
    type: person
    tagline: Economist | Trinity College Dublin
    description: I’m an Assistant Professor in Economics and Programme Director of the MSc in Economic Policy at Trinity College Dublin, working on tax, welfare & inequality
    organization: Trinity College Dublin
    social:
      twitter: barratree
  theme:
    mode: system
    pack: minimal
    colors:
      primary: ""
      secondary: ""
      neutral: ""
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: © {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
  seo:
    title: Barra Roantree | Trinity Colelge Dublin
    location:
      address:
        street: College Green
        city: Dublin 2
        region: Dublin
        country: Ireland
